### PR TITLE
Take 2!

### PR DESCRIPTION
**Pull request by markekraus**
ok how now?

### CODE REVIEW

**Comment by Velocet** [comment]
I am really new to Git... and i think i dunno how to merge this :/

**Comment by markekraus** [comment]
Go to this page https://github.com/Velocet/PowerShell/pull/2 and click the big green merge button :)

**Review by Velocet — APPROVED** [review]

**Comment by Velocet** [comment]
I changed some small things and would like to publish this to PowerShellGallery as soon as you are ok with this version 👍 
Thanks for the contribution. At first i didn't liked the missing return statement but it totally makes sense to write it that way. Thank you!

**Comment by markekraus** [comment]
Looks good! Though, I would have stuck with DeviceName as the property so it is consistent between the two functions. The idea is that you expanded to more functions for this and DeviceName is used in all of them to mean the same thing and have the same type of data, you could pipe the output of any of the functions to the others and it would continue to work.

One small thing to fix is that you changed the DeviceName to Device in the body of the function but not in the Comment Based Help:

Lines 37 and 107
https://github.com/Velocet/PowerShell/blob/master/Velocet/Scripts/Wrapper-smartctl.ps1#L107
https://github.com/Velocet/PowerShell/blob/master/Velocet/Scripts/Wrapper-smartctl.ps1#L37

As for return, it is a bit odd to get used to at first. But write-output is best practice. Return is still useful for short circuiting, but since you may want to send more than one thing to the output stream write-output provides greater flexibility. :)

**Comment by Velocet** [comment]
Yeah.. deleted everything tonight thanks to GIT. I really hate how this works! Never ever worked with a VCS that fucked me up that much. So i lost a lot of work. I deleted your branch since everything was merged but that also deleted everything here and reverted to your version.

I reverted to DeviceName (more consistent). Was just playing around. Also added the script to PowerShell Gallery and added you as an Author. Thanks for your contribution! 👍

**Pull request merged**
